api7/wasm-nginx-module

- src/http/ngx_http_wasm_api.c
- t/http_req_header.t
- t/testdata/http_header/main.go
Closes #47
Signed-off-by: tzssangglass <tzssangglass@gmail.com>
> feat: support get scheme for h2 request header

- proxy_wasm_abi.md
- src/http/ngx_http_wasm_api.c
- t/property.t
- t/testdata/property/main.go
Support get Nginx variables by GetProperty. #53
> feat: support get porperty to get nginx variables

- src/http/ngx_http_wasm_api.c
- t/testdata/http_header/main.go
> change: no longer support underscore in the header name

- src/http/ngx_http_wasm_api.c
- t/http_req_header.t
Signed-off-by: tzssangglass <tzssangglass@gmail.com>
> chore: tweak the output of get scheme (support HTTP1.1)

- t/http_call.t
See:
https://github.com/api7/wasm-nginx-module/runs/5091098477?check_suite_focus=true
> test: increase timeout to avoid CI failure

- README.md
> docs: add APISIX in the front page

- README.md
- lib/resty/proxy-wasm.lua
- src/http/ngx_http_wasm_api.c
- src/http/ngx_http_wasm_module.c
- t/http_resp_body.t
- t/testdata/http_body/main.go
> feat: get response body

- src/http/ngx_http_wasm_api.c
- src/vm/wasmtime.c
> fix: some issues detected by linter

- README.md
> chore: WASM => Wasm

- install-wasmtime.sh
- src/vm/wasmtime.c
> chore: upgrade wasmtime to 0.35.1

- .github/workflows/test.yml
- src/http/ngx_http_wasm_module.c
> ci: add ubsan check

- install-wasmtime.sh
> feat: support compiling under arm64 architecture

- .github/workflows/test.yml
> ci: upgrade tinygo to 0.22

- src/http/ngx_http_wasm_api.c
- src/http/ngx_http_wasm_call.c
- t/http_req_header.t
- t/http_resp_header.t
- t/testdata/http_header/main.go
> feat: allow setting request/response pseudo header

- .github/workflows/test.yml
- .gitignore
- .licenserc.yaml
- Makefile
- src/http/ngx_http_wasm_api.c
- src/http/ngx_http_wasm_api_def.h
- src/http/ngx_http_wasm_api_wasmtime.h
- src/http/ngx_http_wasm_module.c
- t/rust/fault-injection.t
- t/testdata/rust/fault-injection/Cargo.lock
- t/testdata/rust/fault-injection/Cargo.toml
- t/testdata/rust/fault-injection/fault_injection.rs
See https://github.com/apache/apisix-ingress-controller/issues/1004
> feat: adapt proxy-wasm-rust-sdk 0.2.0

- README.md
> docs: fix library path when building with WasmEdge

- .github/workflows/test.yml
> ci: fix broken step

- src/http/ngx_http_wasm_module.c
- t/http_lifecycle.t
> fix: reset queue when destory hwp_ctx->pool

- src/vm/wasmtime.c
- t/hup.t
> fix(wasmtime): avoid crash during Nginx reload

- install-wasmtime.sh
> chore: upgrade wasmtime to 0.38.1

- install-wasmedge.sh
> chore: use WasmEdge 0.10.0

- .gitattributes
- .licenserc.yaml
> chore: correct linguist language

- lib/resty/proxy-wasm.lua
- src/http/ngx_http_wasm_api.c
- src/proxy_wasm/proxy_wasm_types.h
> fix: segmentation fault due to invalid cast, wrong debug log (#132)

- .github/workflows/license-checker.yml
> chore: remove wrong license
